#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
repo_root=$(git -C "$script_dir" rev-parse --show-toplevel)
remote=$(git -C "$repo_root" remote get-url origin 2>/dev/null || true)
case "$(uname -s)/$(uname -m)" in
  Darwin/arm64)
    runner_root=${OCTACITY_RUNNER_ROOT:-$HOME/.octacity-runner}
    backend_label=octacity-microsandbox
    ;;
  Linux/aarch64|Linux/arm64)
    runner_root=${OCTACITY_RUNNER_ROOT:-/opt/octacity-runner}
    backend_label=octacity-native
    ;;
  *)
    printf 'unsupported runner host: %s/%s\n' "$(uname -s)" "$(uname -m)" >&2
    exit 1
    ;;
esac
runner_dir=$runner_root/actions-runner
ENV_FILE=$runner_root/registration.env

banner "OctaCity released-Agent runner"

stage "Verify the backend host"
say "The real backend contract must pass before this machine can accept a release job."
"$script_dir/preflight-backend-runner.sh"
pause "Preflight passed. Press Enter to register the runner."

stage "Open the GitHub runner registration page"
default_repository=${remote%.git}
default_repository=${default_repository/git@github.com:/https://github.com/}
note "Press Enter to use: $default_repository"
ask REPOSITORY_URL "Published repository URL:"
REPOSITORY_URL=${REPOSITORY_URL:-$default_repository}
[[ $REPOSITORY_URL == https://github.com/*/* ]] || {
  warn "expected an https://github.com/OWNER/REPOSITORY URL"
  exit 1
}
write_env REPOSITORY_URL "$REPOSITORY_URL"
repository_path=${REPOSITORY_URL#https://github.com/}
open_url "https://github.com/$repository_path/settings/actions/runners/new"
step "Choose the current operating system and ARM64 architecture."
step "Copy only the one-hour registration token shown in GitHub's configure command."
pause "The registration page is ready?"

stage "Register an ephemeral runner"
ask_secret REGISTRATION_TOKEN "Paste the one-time registration token:"
[[ -n $REGISTRATION_TOKEN ]] || {
  warn "registration token cannot be empty"
  exit 1
}
[[ ! -e $runner_dir/.runner ]] || {
  warn "$runner_dir is already configured; use a fresh runner installation before retrying"
  exit 1
}
runner_name="octacity-${backend_label#octacity-}-$(hostname)-$(date +%s)"
(
  cd "$runner_dir"
  ./config.sh --unattended --ephemeral \
    --url "$REPOSITORY_URL" \
    --token "$REGISTRATION_TOKEN" \
    --name "$runner_name" \
    --labels "$backend_label" \
    --work _work
)
unset REGISTRATION_TOKEN
# config.sh snapshots the invoking shell's PATH, so restore the audited backend
# environment after registration rather than trusting that incidental value.
"$script_dir/preflight-backend-runner.sh" --write-only
say "Registered $runner_name with label $backend_label."

stage "Run one release-gate job"
open_url "https://github.com/$repository_path/actions/workflows/backend-contracts.yml"
step "Start the wizard on the other backend host before dispatching the workflow."
step "In Run workflow choose the published branch and suite 'released-agent', then click Run workflow."
warn "Keep this terminal open until the runner exits after its single job."
pause "Press Enter when the other runner is ready and the workflow can be dispatched."
while IFS='=' read -r name value; do
  [[ $name =~ ^OCTACITY_[A-Z0-9_]+$ ]] || {
    warn "invalid runner environment key: $name"
    exit 1
  }
  printf -v "$name" '%s' "$value"
  export "${name?}"
done < "$runner_dir/.env"
PATH=$(<"$runner_dir/.path")
export PATH
if [[ $(uname -s) == Linux ]]; then
  sudo --preserve-env=OCTACITY_CONTRACT_OCTA_RELEASE_ROOT,OCTACITY_CONTRACT_WORKSPACE_BYTES,OCTACITY_CONTRACT_NATIVE_CGROUP_ROOT,OCTACITY_CONTRACT_NATIVE_WORK_ROOT,OCTACITY_RELEASE_NATIVE_CACHE_ROOT,OCTACITY_CONTRACT_NATIVE_BWRAP,OCTACITY_CONTRACT_NATIVE_PATH \
    /usr/local/sbin/octacity-in-cgroup "$USER" "$runner_dir/run.sh"
else
  "$runner_dir/run.sh"
fi

finish
