[package]
name = "octacity-server-api-rest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Management REST API adapter for the OctaCity server"

[dependencies]
async-trait.workspace = true
axum.workspace = true
octacity-server-application = { path = "../../application" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
