[package]
name = "octacity-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
octacity-config = { path = "../octacity-config" }
octacity-runner = { path = "../octacity-runner" }
octacity-source = { path = "../octacity-source" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
