//! Async transport adapter for the shared `octa-runner-protocol` crate.
//!
//! Wire DTOs and schema versions remain owned by Octa. OctaCity adds only
//! bounded asynchronous framing and the event shape it must validate before
//! forwarding data to the control plane.

use octa_runner_protocol::{MAX_RUNNER_INPUT_FRAME_BYTES, RunnerCommand};
#[cfg(test)]
use octa_runner_protocol::{
  RUNNER_EVENT_SCHEMA_VERSION, RUNNER_INPUT_SCHEMA_V1, RUNNER_OUTPUT_SCHEMA_V1, RUNNER_PROTOCOL_VERSION,
};
use serde::Deserialize;
use thiserror::Error;
use tokio::io::{AsyncBufReadExt as _, AsyncRead, AsyncReadExt as _, AsyncWrite, AsyncWriteExt as _, BufReader};

/// Agent-side upper bound for a single runner output frame.
pub const MAX_RUNNER_OUTPUT_FRAME_BYTES: usize = 16 * 1024 * 1024;

/// Runner envelope specialized with the event and result payloads consumed by the agent.
pub type RunnerMessage = octa_runner_protocol::RunnerMessage<String, RunnerEvent, Vec<serde_json::Value>>;

/// Minimal event header retained before category-specific data reaches the server.
#[derive(Clone, Debug, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct RunnerEvent {
  /// Version of the structured event schema.
  pub schema_version: u16,
  /// Monotonic sequence number assigned by the runner.
  pub sequence: u64,
  /// RFC 3339 timestamp generated by the runner.
  pub timestamp: String,
  /// Semantic event category used by downstream consumers.
  pub category: String,
  /// Category-specific event payload.
  pub data: serde_json::Map<String, serde_json::Value>,
}

#[derive(Debug, Error)]
/// Failure while reading or writing the runner JSONL protocol.
pub enum RunnerProtocolError {
  #[error("runner protocol I/O failed: {0}")]
  /// An underlying runner stream failed.
  Io(#[source] std::io::Error),
  #[error("runner output frame exceeds the {MAX_RUNNER_OUTPUT_FRAME_BYTES}-byte limit")]
  /// One output frame exceeded the agent-side size bound.
  FrameTooLarge,
  #[error("runner output frame is not terminated by a newline")]
  /// The runner closed stdout in the middle of a JSONL frame.
  UnterminatedFrame,
  #[error("runner output is not valid protocol JSON: {0}")]
  /// A complete protocol frame contained invalid JSON.
  Json(#[source] Box<serde_json::Error>),
  #[error("runner input frame exceeds the {MAX_RUNNER_INPUT_FRAME_BYTES}-byte limit")]
  /// A serialized command exceeded the shared input size bound.
  InputTooLarge,
}

/// Reads one newline-terminated, size-bounded runner message.
pub async fn read_message<R: AsyncRead + Unpin>(
  reader: &mut BufReader<R>,
) -> Result<Option<RunnerMessage>, RunnerProtocolError> {
  let mut frame = Vec::new();
  let mut limited = (&mut *reader).take((MAX_RUNNER_OUTPUT_FRAME_BYTES + 1) as u64);
  let read = limited
    .read_until(b'\n', &mut frame)
    .await
    .map_err(RunnerProtocolError::Io)?;
  if read == 0 {
    return Ok(None);
  }
  if read > MAX_RUNNER_OUTPUT_FRAME_BYTES {
    return Err(RunnerProtocolError::FrameTooLarge);
  }
  if !frame.ends_with(b"\n") {
    return Err(RunnerProtocolError::UnterminatedFrame);
  }
  serde_json::from_slice(&frame)
    .map(Some)
    .map_err(|error| RunnerProtocolError::Json(Box::new(error)))
}

/// Serializes and flushes one bounded command to the runner.
pub async fn write_command<W: AsyncWrite + Unpin>(
  writer: &mut W,
  command: &RunnerCommand,
) -> Result<(), RunnerProtocolError> {
  let mut frame = serde_json::to_vec(command).map_err(|error| RunnerProtocolError::Json(Box::new(error)))?;
  frame.push(b'\n');
  if frame.len() > MAX_RUNNER_INPUT_FRAME_BYTES {
    return Err(RunnerProtocolError::InputTooLarge);
  }
  writer.write_all(&frame).await.map_err(RunnerProtocolError::Io)?;
  writer.flush().await.map_err(RunnerProtocolError::Io)
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn shared_schemas_match_the_supported_protocol_versions() {
    let input: serde_json::Value = serde_json::from_str(RUNNER_INPUT_SCHEMA_V1).unwrap();
    let output: serde_json::Value = serde_json::from_str(RUNNER_OUTPUT_SCHEMA_V1).unwrap();

    assert_eq!(
      input["$defs"]["start"]["properties"]["protocol_version"]["const"],
      RUNNER_PROTOCOL_VERSION
    );
    assert_eq!(
      output["$defs"]["hello"]["properties"]["protocol_version"]["const"],
      RUNNER_PROTOCOL_VERSION
    );
    assert_eq!(
      output["$defs"]["event"]["properties"]["event"]["properties"]["schema_version"]["const"],
      RUNNER_EVENT_SCHEMA_VERSION
    );
  }

  #[tokio::test]
  async fn round_trips_a_bounded_command_and_message() {
    let command = RunnerCommand::Cancel {
      request_id: "job-1-attempt-1".to_owned(),
    };
    let mut encoded = Vec::new();
    write_command(&mut encoded, &command).await.unwrap();
    assert_eq!(encoded.last(), Some(&b'\n'));

    let mut reader = BufReader::new(
      &br#"{"type":"accepted","request_id":"job-1-attempt-1"}
"#[..],
    );
    assert_eq!(
      read_message(&mut reader).await.unwrap(),
      Some(RunnerMessage::Accepted {
        request_id: "job-1-attempt-1".to_owned()
      })
    );
  }

  #[tokio::test]
  async fn rejects_unterminated_and_oversized_frames() {
    let mut unterminated = BufReader::new(&b"{}"[..]);
    assert!(matches!(
      read_message(&mut unterminated).await,
      Err(RunnerProtocolError::UnterminatedFrame)
    ));

    let oversized = vec![b'x'; MAX_RUNNER_OUTPUT_FRAME_BYTES + 1];
    let mut oversized = BufReader::new(oversized.as_slice());
    assert!(matches!(
      read_message(&mut oversized).await,
      Err(RunnerProtocolError::FrameTooLarge)
    ));
  }
}
