import { execFile } from 'node:child_process';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const MAX_EXPORTED_OPENAPI_BYTES = 16 * 1024 * 1024;
const execFileAsync = promisify(execFile);
const uiRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repositoryRoot = path.resolve(uiRoot, '..');
const generatedDirectory = path.join(uiRoot, '.generated', 'api');
const generatedTypes = path.join(generatedDirectory, 'schema.d.ts');
const generatedConstraints = path.join(generatedDirectory, 'constraints.ts');

async function exportOpenApi() {
  const { stdout } = await execFileAsync(
    'cargo',
    ['run', '--quiet', '--package', 'octacity-server-api-rest', '--example', 'export_openapi'],
    {
      cwd: repositoryRoot,
      encoding: 'utf8',
      maxBuffer: MAX_EXPORTED_OPENAPI_BYTES,
    },
  );

  return JSON.parse(stdout);
}

async function loadOpenApi() {
  const suppliedSchema = process.env.OCTACITY_OPENAPI_SCHEMA_FILE;
  if (suppliedSchema === undefined) {
    return exportOpenApi();
  }
  const schemaPath = path.resolve(uiRoot, suppliedSchema);
  const metadata = await stat(schemaPath);
  if (!metadata.isFile() || metadata.size > MAX_EXPORTED_OPENAPI_BYTES) {
    throw new Error('Supplied management API schema must be a bounded regular file.');
  }
  return JSON.parse(await readFile(schemaPath, 'utf8'));
}

async function generateApiTypes() {
  const document = await loadOpenApi();
  const declarations = astToString(await openapiTS(document));
  const constraints = generateConstraints(document);

  await mkdir(generatedDirectory, { recursive: true });
  await Promise.all([
    writeFile(generatedTypes, declarations, 'utf8'),
    writeFile(generatedConstraints, constraints, 'utf8'),
  ]);
}

function generateConstraints(document) {
  const parameters = document.paths?.['/api/v1/audit-facts']?.get?.parameters;
  const actorKinds = document.components?.schemas?.AuditActorKind?.enum;
  if (!Array.isArray(parameters) || !actorKinds?.every((value) => typeof value === 'string')) {
    throw new Error('Audit query constraints are missing from the management API schema.');
  }

  const parameter = (name) => {
    const found = parameters.find(
      (candidate) => candidate.name === name && candidate.in === 'query',
    );
    if (found === undefined) throw new Error(`Audit query parameter ${name} is missing.`);
    return found;
  };
  const positiveInteger = (value, label) => {
    if (!Number.isSafeInteger(value) || value < 1) {
      throw new Error(`${label} must be a positive integer in the management API schema.`);
    }
    return value;
  };
  const maximumBytes = (name) =>
    positiveInteger(parameter(name).schema?.['x-max-utf8-bytes'], `${name} byte limit`);
  const limit = parameter('limit').schema;
  const values = {
    actorIdentityMaximumBytes: maximumBytes('actor_identity'),
    defaultPageSize: positiveInteger(limit?.default, 'Audit default page size'),
    operationMaximumBytes: maximumBytes('operation'),
    requestIdentityMaximumBytes: maximumBytes('request_identity'),
    targetIdentityMaximumBytes: maximumBytes('target_identity'),
    targetKindMaximumBytes: maximumBytes('target_kind'),
  };

  return `// Generated by scripts/generate-api.mjs. Do not edit.\n\nexport const AUDIT_ACTOR_KINDS = ${JSON.stringify(actorKinds, null, 2)} as const;\n\nexport const AUDIT_QUERY_CONSTRAINTS = ${JSON.stringify(values, null, 2)} as const;\n`;
}

try {
  await generateApiTypes();
} catch (error) {
  const details = error instanceof Error ? (error.stack ?? error.message) : String(error);
  process.stderr.write(`Failed to generate management API types.\n${details}\n`);
  process.exitCode = 1;
}
