use std::fmt;

use octacity_protocol::AgentInventory;
use octacity_server_domain::{
  AgentId, AgentName, EnrollmentCredentialId, PoolId, PoolVersion, RegistrationCredentialId, Timestamp,
};
use serde::{Deserialize, Serialize};
use sha2::{Digest as _, Sha256};
use zeroize::Zeroizing;

use crate::{MutationDisposition, RegistrationEpoch, StoreError, StoreInputError, StoreOperation};

/// Maximum UTF-8 bytes in one extensible operating-system or architecture label.
pub const MAX_AGENT_PLATFORM_LABEL_BYTES: usize = 64;
/// Maximum encoded bytes in one scheduler-visible Agent inventory document.
pub const MAX_AGENT_INVENTORY_BYTES: usize = 256 * 1_024;

/// A high-entropy bearer credential whose formatting never reveals its bytes.
///
/// Callers must construct the 32 bytes with a cryptographically secure random
/// generator. The store persists only [`CredentialDigest`].
#[derive(Clone)]
pub struct CredentialSecret(Zeroizing<[u8; 32]>);

impl CredentialSecret {
  /// Wraps 256 bits generated by a cryptographically secure random source.
  #[must_use]
  pub fn from_bytes(bytes: [u8; 32]) -> Self {
    Self(Zeroizing::new(bytes))
  }

  /// Derives the irreversible, domain-separated value stored by adapters.
  #[must_use]
  pub fn digest(&self) -> CredentialDigest {
    let mut hash = Sha256::new();
    hash.update(b"octacity.agent-credential.v1\0");
    hash.update(self.0.as_slice());
    CredentialDigest(hash.finalize().into())
  }
}

impl fmt::Debug for CredentialSecret {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter.write_str("CredentialSecret([REDACTED])")
  }
}

impl fmt::Display for CredentialSecret {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter.write_str("[REDACTED]")
  }
}

impl PartialEq for CredentialSecret {
  fn eq(&self, other: &Self) -> bool {
    self.digest().matches(other.digest())
  }
}

impl Eq for CredentialSecret {}

/// Fixed-size irreversible verifier for an Agent bearer credential.
#[derive(Clone, Copy, Eq, Hash, PartialEq)]
pub struct CredentialDigest([u8; 32]);

impl CredentialDigest {
  /// Constructs a digest loaded from trusted durable state.
  #[must_use]
  pub const fn from_bytes(bytes: [u8; 32]) -> Self {
    Self(bytes)
  }

  /// Returns bytes suitable for persistence, never the original credential.
  #[must_use]
  pub const fn as_bytes(self) -> [u8; 32] {
    self.0
  }

  /// Compares two digests without data-dependent early exit.
  #[must_use]
  pub fn matches(self, other: Self) -> bool {
    let difference = self
      .0
      .iter()
      .zip(other.0)
      .fold(0_u8, |difference, (left, right)| difference | (*left ^ right));
    difference == 0
  }
}

impl fmt::Debug for CredentialDigest {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter.write_str("CredentialDigest([REDACTED])")
  }
}

/// Provider-neutral Agent host platform used by enrollment admission policy.
#[derive(Clone, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
pub struct AgentPlatform {
  operating_system: String,
  architecture: String,
}

impl AgentPlatform {
  /// Constructs an extensible canonical platform from bounded lowercase labels.
  pub fn new(operating_system: impl Into<String>, architecture: impl Into<String>) -> Result<Self, StoreInputError> {
    let operating_system = operating_system.into();
    let architecture = architecture.into();
    if !valid_platform_label(&operating_system) || !valid_platform_label(&architecture) {
      return Err(StoreInputError::InvalidAgentPlatform);
    }
    Ok(Self {
      operating_system,
      architecture,
    })
  }

  /// Returns the canonical operating-system label.
  #[must_use]
  pub fn operating_system(&self) -> &str {
    &self.operating_system
  }

  /// Returns the canonical architecture label.
  #[must_use]
  pub fn architecture(&self) -> &str {
    &self.architecture
  }
}

/// Platform restriction carried by one enrollment credential.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case", tag = "policy", content = "platform")]
pub enum ExpectedAgentPlatform {
  /// Any syntactically valid Agent platform may consume the credential.
  Any,
  /// Only one exact operating-system and architecture pair may consume it.
  Exact(AgentPlatform),
}

impl ExpectedAgentPlatform {
  /// Reports whether a presented platform satisfies this policy.
  #[must_use]
  pub fn accepts(&self, actual: &AgentPlatform) -> bool {
    match self {
      Self::Any => true,
      Self::Exact(expected) => expected == actual,
    }
  }
}

/// Complete atomic request to issue one single-use enrollment credential.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IssueAgentEnrollment {
  /// Stable credential and idempotency identity.
  pub credential_id: EnrollmentCredentialId,
  /// Plaintext returned by the trusted caller and never persisted.
  pub credential: CredentialSecret,
  /// Agent Pool to which successful enrollment binds the Agent.
  pub pool_id: PoolId,
  /// Immutable Pool policy version captured when the credential is issued.
  pub pool_version: PoolVersion,
  /// Platform admission policy checked when the credential is consumed.
  pub expected_platform: ExpectedAgentPlatform,
  /// Authoritative issue time.
  pub issued_at: Timestamp,
  /// Exclusive credential expiry.
  pub expires_at: Timestamp,
}

impl IssueAgentEnrollment {
  /// Validates a bounded credential lifetime.
  pub fn new(
    credential_id: EnrollmentCredentialId,
    credential: CredentialSecret,
    pool_id: PoolId,
    pool_version: PoolVersion,
    expected_platform: ExpectedAgentPlatform,
    issued_at: Timestamp,
    expires_at: Timestamp,
  ) -> Result<Self, StoreError> {
    let request = Self {
      credential_id,
      credential,
      pool_id,
      pool_version,
      expected_platform,
      issued_at,
      expires_at,
    };
    request.validate()?;
    Ok(request)
  }

  /// Revalidates invariants after construction of this mutable request value.
  pub fn validate(&self) -> Result<(), StoreError> {
    require_credential_window(StoreOperation::IssueAgentEnrollment, self.issued_at, self.expires_at)
  }
}

/// Durable result of issuing an enrollment credential.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IssueAgentEnrollmentOutcome {
  /// Whether this request was newly applied or exactly replayed.
  pub disposition: MutationDisposition,
  /// Stable credential identity.
  pub credential_id: EnrollmentCredentialId,
  /// Bound Agent Pool.
  pub pool_id: PoolId,
  /// Immutable Pool policy version captured at issuance.
  pub pool_version: PoolVersion,
  /// Exclusive credential expiry.
  pub expires_at: Timestamp,
}

/// Authority accepted when creating a fresh Agent registration epoch.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum AgentRegistrationProof {
  /// Single-use bootstrap authority for an Agent's first registration.
  Enrollment {
    /// Enrollment credential identity.
    credential_id: EnrollmentCredentialId,
    /// Enrollment bearer secret.
    credential: CredentialSecret,
  },
  /// Current registration authority for process restart and credential rotation.
  Registration {
    /// Current registration credential identity.
    credential_id: RegistrationCredentialId,
    /// Current epoch that must still be authoritative.
    epoch: RegistrationEpoch,
    /// Current registration bearer secret.
    credential: CredentialSecret,
  },
}

/// Fresh credential material generated for one new registration epoch.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct FreshRegistrationCredential {
  /// Stable identity of the fresh registration and its idempotency record.
  pub id: RegistrationCredentialId,
  /// Fresh bearer secret; adapters persist only its digest.
  pub secret: CredentialSecret,
}

/// Authoritative validity window for one registration epoch.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RegistrationValidity {
  /// Authoritative registration time.
  pub registered_at: Timestamp,
  /// Exclusive registration expiry.
  pub expires_at: Timestamp,
}

/// Complete atomic request to create and supersede an Agent registration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RegisterAgent {
  /// Identity of the fresh registration and its idempotency record.
  pub credential_id: RegistrationCredentialId,
  /// Fresh bearer secret; adapters persist only its digest.
  pub credential: CredentialSecret,
  /// Stable Agent identity retained across process registrations.
  pub agent_id: AgentId,
  /// User-visible Agent name selected at initial enrollment.
  pub agent_name: AgentName,
  /// Enrollment or current-registration authority.
  pub proof: AgentRegistrationProof,
  /// Platform measured by the registering process.
  pub platform: AgentPlatform,
  /// Complete validated scheduler-visible inventory.
  pub inventory: AgentInventory,
  /// Authoritative registration time.
  pub registered_at: Timestamp,
  /// Exclusive registration expiry.
  pub expires_at: Timestamp,
}

impl RegisterAgent {
  /// Validates the registration lifetime and structured inventory envelope.
  pub fn new(
    credential: FreshRegistrationCredential,
    agent_id: AgentId,
    agent_name: AgentName,
    proof: AgentRegistrationProof,
    platform: AgentPlatform,
    inventory: AgentInventory,
    validity: RegistrationValidity,
  ) -> Result<Self, StoreError> {
    let request = Self {
      credential_id: credential.id,
      credential: credential.secret,
      agent_id,
      agent_name,
      proof,
      platform,
      inventory,
      registered_at: validity.registered_at,
      expires_at: validity.expires_at,
    };
    request.validate()?;
    Ok(request)
  }

  /// Revalidates the lifetime and complete bounded inventory at an adapter seam.
  pub fn validate(&self) -> Result<(), StoreError> {
    require_credential_window(StoreOperation::RegisterAgent, self.registered_at, self.expires_at)?;
    if self.inventory.validate().is_err() {
      return Err(StoreError::invalid(
        StoreOperation::RegisterAgent,
        StoreInputError::InvalidAgentInventory,
      ));
    }
    if serde_json::to_vec(&self.inventory).map_or(true, |encoded| encoded.len() > MAX_AGENT_INVENTORY_BYTES) {
      return Err(StoreError::invalid(
        StoreOperation::RegisterAgent,
        StoreInputError::JsonDocumentTooLarge,
      ));
    }
    Ok(())
  }
}

/// Durable result of creating one fresh Agent registration epoch.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AgentRegistrationOutcome {
  /// Whether this request was newly applied or exactly replayed.
  pub disposition: MutationDisposition,
  /// Fresh registration credential identity.
  pub credential_id: RegistrationCredentialId,
  /// Stable Agent identity.
  pub agent_id: AgentId,
  /// Monotonic epoch assigned to this process registration.
  pub registration_epoch: RegistrationEpoch,
  /// Agent Pool retained from enrollment.
  pub pool_id: PoolId,
  /// Immutable Pool policy version retained from enrollment.
  pub pool_version: PoolVersion,
  /// Exclusive registration expiry.
  pub expires_at: Timestamp,
}

/// Authentication request for one purportedly current registration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthenticateAgentRegistration {
  /// Presented registration identity.
  pub credential_id: RegistrationCredentialId,
  /// Presented registration bearer secret.
  pub credential: CredentialSecret,
  /// Authoritative authentication time used for expiry evaluation.
  pub authenticated_at: Timestamp,
}

/// Non-secret current registration context returned after authentication.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AuthenticatedAgentRegistration {
  /// Stable Agent identity.
  pub agent_id: AgentId,
  /// Current registration epoch.
  pub registration_epoch: RegistrationEpoch,
  /// Pool to which the Agent remains bound.
  pub pool_id: PoolId,
  /// Immutable Pool policy version retained from enrollment.
  pub pool_version: PoolVersion,
  /// Static host capacity retained from the validated registration inventory.
  pub host_capacity: octacity_protocol::HostCapacity,
  /// Exclusive registration expiry.
  pub expires_at: Timestamp,
}

/// Enrollment or registration identity selected for explicit revocation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AgentCredentialTarget {
  /// Revoke an unused enrollment credential.
  Enrollment(EnrollmentCredentialId),
  /// Revoke an Agent registration credential.
  Registration(RegistrationCredentialId),
}

/// Idempotent explicit Agent credential revocation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RevokeAgentCredential {
  /// Credential selected for revocation.
  pub target: AgentCredentialTarget,
  /// Authoritative revocation time.
  pub revoked_at: Timestamp,
}

fn require_credential_window(
  operation: StoreOperation,
  issued_at: Timestamp,
  expires_at: Timestamp,
) -> Result<(), StoreError> {
  if expires_at <= issued_at {
    return Err(StoreError::invalid(operation, StoreInputError::InvalidCredentialWindow));
  }
  Ok(())
}

fn valid_platform_label(value: &str) -> bool {
  !value.is_empty()
    && value.len() <= MAX_AGENT_PLATFORM_LABEL_BYTES
    && value
      .bytes()
      .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_' | b'.'))
}
