use octacity_server_domain::{AgentId, JobId, LeaseId, PoolId, Timestamp};
use serde_json::Value;
use sha2::{Digest as _, Sha256};

use crate::model::{canonical_json, require_bounded_json};
use crate::{
  EventDigest, EventSequence, JobEventKind, LeaseFence, MAX_JOB_EVENT_BATCH_BYTES, MAX_JOB_EVENT_BATCH_SIZE,
  MAX_JOB_EVENT_PAYLOAD_BYTES, MutationDisposition, RegistrationEpoch, StoreError, StoreInputError, StoreOperation,
};

/// Complete atomic input for compatible ready-Job selection and Lease creation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct JobClaim {
  /// New opaque Lease identity generated by the caller.
  pub lease_id: LeaseId,
  /// Secret opaque fence generated independently of the Lease identity.
  pub fence: LeaseFence,
  /// Accepting Agent identity.
  pub agent_id: AgentId,
  /// Current Agent process registration.
  pub registration_epoch: RegistrationEpoch,
  /// Pool to which the current Agent registration belongs.
  pub pool_id: PoolId,
  /// Authoritative claim time.
  pub claimed_at: Timestamp,
  /// Initial Lease expiry.
  pub expires_at: Timestamp,
}

impl JobClaim {
  /// Validates one bounded Lease window.
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    lease_id: LeaseId,
    fence: LeaseFence,
    agent_id: AgentId,
    registration_epoch: RegistrationEpoch,
    pool_id: PoolId,
    claimed_at: Timestamp,
    expires_at: Timestamp,
  ) -> Result<Self, StoreError> {
    let request = Self {
      lease_id,
      fence,
      agent_id,
      registration_epoch,
      pool_id,
      claimed_at,
      expires_at,
    };
    request.validate()?;
    Ok(request)
  }

  /// Revalidates the Lease window at an adapter seam.
  pub fn validate(self) -> Result<(), StoreError> {
    if self.expires_at <= self.claimed_at {
      return Err(StoreError::invalid(
        StoreOperation::ClaimReadyJob,
        StoreInputError::InvalidLeaseWindow,
      ));
    }
    Ok(())
  }
}

/// Durable ownership data returned with a successful ready-Job claim.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LeaseGrant {
  /// Newly current Lease identity.
  pub lease_id: LeaseId,
  /// Secret fence required by every ownership mutation.
  pub fence: LeaseFence,
  /// Job exclusively owned by the Lease.
  pub job_id: JobId,
  /// Owning Agent identity.
  pub agent_id: AgentId,
  /// Owning Agent process epoch.
  pub registration_epoch: RegistrationEpoch,
  /// Selected Pool recorded by placement.
  pub pool_id: PoolId,
  /// Current Lease deadline.
  pub expires_at: Timestamp,
}

/// Outcome of one bounded compatible ready-Job claim.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum JobClaimOutcome {
  /// No compatible ready Job was visible at the transaction point.
  Empty,
  /// One Job and its newly current Lease committed together.
  Claimed(LeaseGrant),
}

/// Current Lease ownership supplied to fenced mutations.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LeaseAccess {
  /// Current Lease identity.
  pub lease_id: LeaseId,
  /// Secret opaque fence returned with the Lease.
  pub fence: LeaseFence,
  /// Stable Agent identity.
  pub agent_id: AgentId,
  /// Current Agent process epoch.
  pub registration_epoch: RegistrationEpoch,
}

/// One immutable ordered Job event and its exact payload identity.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DurableJobEvent {
  /// Positive sequence within one Job stream.
  sequence: EventSequence,
  /// Stable provider-neutral event classification.
  kind: JobEventKind,
  /// Source-observed time retained independently of persistence time.
  occurred_at: Timestamp,
  /// Bounded validated event payload.
  payload: Value,
  /// Digest of the canonical event kind, time, and bounded payload.
  digest: EventDigest,
}

impl DurableJobEvent {
  /// Validates the payload and computes its canonical event digest.
  pub fn new(
    sequence: EventSequence,
    kind: JobEventKind,
    occurred_at: Timestamp,
    payload: Value,
  ) -> Result<Self, StoreInputError> {
    require_bounded_json(
      &payload,
      MAX_JOB_EVENT_PAYLOAD_BYTES,
      StoreInputError::EventPayloadTooLarge,
    )?;
    let canonical_payload = canonical_json(payload);
    let encoded = serde_json::to_vec(&(kind.as_str(), occurred_at.unix_millis(), &canonical_payload))
      .map_err(|_| StoreInputError::EventPayloadTooLarge)?;
    let digest = EventDigest::from_bytes(Sha256::digest(encoded).into());
    Ok(Self {
      sequence,
      kind,
      occurred_at,
      payload: canonical_payload,
      digest,
    })
  }

  /// Returns the positive sequence within the Job stream.
  #[must_use]
  pub const fn sequence(&self) -> EventSequence {
    self.sequence
  }

  /// Returns the stable provider-neutral event classification.
  #[must_use]
  pub const fn kind(&self) -> &JobEventKind {
    &self.kind
  }

  /// Returns the source-observed event time.
  #[must_use]
  pub const fn occurred_at(&self) -> Timestamp {
    self.occurred_at
  }

  /// Borrows the validated canonical payload.
  #[must_use]
  pub const fn payload(&self) -> &Value {
    &self.payload
  }

  /// Returns the digest computed from the complete canonical event content.
  #[must_use]
  pub const fn digest(&self) -> EventDigest {
    self.digest
  }
}

/// Complete atomic input for one contiguous idempotent Job-event append.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AppendJobEvents {
  /// Current fenced ownership.
  pub lease: LeaseAccess,
  /// Contiguous batch, which may include an already durable replay prefix.
  pub events: Vec<DurableJobEvent>,
  /// Authoritative acceptance time used to reject expired Lease ownership.
  pub accepted_at: Timestamp,
}

impl AppendJobEvents {
  /// Validates sequence continuity within one batch.
  pub fn new(lease: LeaseAccess, events: Vec<DurableJobEvent>, accepted_at: Timestamp) -> Result<Self, StoreError> {
    let request = Self {
      lease,
      events,
      accepted_at,
    };
    request.validate()?;
    Ok(request)
  }

  /// Revalidates the batch bound and sequence continuity at an adapter seam.
  pub fn validate(&self) -> Result<(), StoreError> {
    let events = &self.events;
    if events.is_empty() {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::EmptyEventBatch,
      ));
    }
    if events.len() > MAX_JOB_EVENT_BATCH_SIZE {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::EventBatchTooLarge,
      ));
    }
    if events
      .iter()
      .try_fold(0_usize, |total, event| {
        serde_json::to_vec(&(
          event.sequence().get(),
          event.kind().as_str(),
          event.occurred_at().unix_millis(),
          event.payload(),
        ))
        .ok()
        .and_then(|encoded| total.checked_add(encoded.len()))
      })
      .is_none_or(|bytes| bytes > MAX_JOB_EVENT_BATCH_BYTES)
    {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::RequestTooLarge,
      ));
    }
    if events
      .windows(2)
      .any(|pair| pair[0].sequence().get().checked_add(1) != Some(pair[1].sequence().get()))
    {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::NonContiguousEventBatch,
      ));
    }
    Ok(())
  }
}

/// Durable cursor returned after one event append.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AppendJobEventsOutcome {
  /// Greatest contiguous sequence now durable.
  pub acknowledged_through: EventSequence,
  /// Number of newly inserted events; an exact replay inserts zero.
  pub inserted: usize,
}

/// Stable terminal classification stored for one completed Job.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum JobCompletionKind {
  /// The Job completed successfully.
  Succeeded,
  /// The Job completed with a classified execution failure.
  Failed,
  /// The Job reached terminal cancellation.
  Cancelled,
}

/// Complete atomic input for terminal Job completion.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct JobCompletion {
  /// Current fenced ownership.
  pub lease: LeaseAccess,
  /// Greatest event sequence declared by the Agent, or `None` for no events.
  pub final_sequence: Option<EventSequence>,
  /// Terminal outcome.
  pub kind: JobCompletionKind,
  /// Authoritative completion time.
  pub completed_at: Timestamp,
}

/// Result of an idempotent terminal completion.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompletionDisposition {
  /// Whether the completion was newly applied or exactly replayed.
  pub disposition: MutationDisposition,
  /// Completed Job identity.
  pub job_id: JobId,
  /// Dependency-unblocked Jobs inserted into the ready queue by this commit.
  pub ready_jobs: Vec<JobId>,
}
