use std::collections::BTreeSet;

use octacity_protocol::{HostSnapshot, SignedEnvelope};
use octacity_server_artifacts::{BuildLogStream, LogChunkManifest};
use octacity_server_domain::{AgentId, AttemptNumber, JobId, LeaseId, PoolId, Timestamp, canonicalize_json};
use octacity_server_job::{JobEvent, JobFailureClass, JobState};
use octacity_server_orchestrator::{AttemptState, BuildState};
use serde_json::Value;
use sha2::{Digest as _, Sha256};

use crate::model::require_bounded_json;
use crate::{
  EventDigest, EventSequence, JobEventKind, LeaseFence, MAX_JOB_EVENT_BATCH_BYTES, MAX_JOB_EVENT_BATCH_SIZE,
  MAX_JOB_EVENT_PAYLOAD_BYTES, MAX_JOB_EVENT_READ_PAGE_SIZE, MutationDisposition, RegistrationEpoch, StoreError,
  StoreInputError, StoreOperation,
};

/// Complete atomic input for compatible ready-Job selection and Lease creation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JobClaim {
  /// New opaque Lease identity generated by the caller.
  pub lease_id: LeaseId,
  /// Secret opaque fence generated independently of the Lease identity.
  pub fence: LeaseFence,
  /// Accepting Agent identity.
  pub agent_id: AgentId,
  /// Current Agent process registration.
  pub registration_epoch: RegistrationEpoch,
  /// Pool to which the current Agent registration belongs.
  pub pool_id: PoolId,
  /// Current Agent capacity and backend health used for compatibility.
  pub snapshot: HostSnapshot,
  /// Authoritative claim time.
  pub claimed_at: Timestamp,
  /// Initial Lease expiry.
  pub expires_at: Timestamp,
}

/// Validated authoritative time window for a newly created Lease.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LeaseWindow {
  /// Time at which ownership begins.
  pub claimed_at: Timestamp,
  /// Initial ownership deadline.
  pub expires_at: Timestamp,
}

impl LeaseWindow {
  /// Creates a positive Lease window.
  pub fn new(claimed_at: Timestamp, expires_at: Timestamp) -> Result<Self, StoreError> {
    let window = Self { claimed_at, expires_at };
    window.validate()?;
    Ok(window)
  }

  fn validate(self) -> Result<(), StoreError> {
    if self.expires_at <= self.claimed_at {
      return Err(StoreError::invalid(
        StoreOperation::ClaimReadyJob,
        StoreInputError::InvalidLeaseWindow,
      ));
    }
    Ok(())
  }
}

impl JobClaim {
  /// Validates one bounded Lease window.
  pub fn new(
    lease_id: LeaseId,
    fence: LeaseFence,
    agent_id: AgentId,
    registration_epoch: RegistrationEpoch,
    pool_id: PoolId,
    snapshot: HostSnapshot,
    window: LeaseWindow,
  ) -> Result<Self, StoreError> {
    let request = Self {
      lease_id,
      fence,
      agent_id,
      registration_epoch,
      pool_id,
      snapshot,
      claimed_at: window.claimed_at,
      expires_at: window.expires_at,
    };
    request.validate()?;
    Ok(request)
  }

  /// Revalidates the Lease window at an adapter seam.
  pub fn validate(&self) -> Result<(), StoreError> {
    LeaseWindow {
      claimed_at: self.claimed_at,
      expires_at: self.expires_at,
    }
    .validate()
  }
}

/// Durable ownership data returned with a successful ready-Job claim.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct LeaseGrant {
  /// Newly current Lease identity.
  pub lease_id: LeaseId,
  /// Secret fence required by every ownership mutation.
  pub fence: LeaseFence,
  /// Job exclusively owned by the Lease.
  pub job_id: JobId,
  /// Positive Build Attempt number bound into the signed JobSpec.
  pub attempt: AttemptNumber,
  /// Owning Agent identity.
  pub agent_id: AgentId,
  /// Owning Agent process epoch.
  pub registration_epoch: RegistrationEpoch,
  /// Selected Pool recorded by placement.
  pub pool_id: PoolId,
  /// Authoritative Lease issue time.
  pub claimed_at: Timestamp,
  /// Current Lease deadline.
  pub expires_at: Timestamp,
  /// Persisted server-signed execution intent for this exact Job and Attempt.
  pub signed_job_spec: SignedEnvelope,
}

/// Outcome of one bounded compatible ready-Job claim.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum JobClaimOutcome {
  /// No compatible ready Job was visible at the transaction point.
  Empty,
  /// One Job and its newly current Lease committed together.
  Claimed(Box<LeaseGrant>),
}

/// Current Lease ownership supplied to fenced mutations.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct LeaseAccess {
  /// Current Lease identity.
  pub lease_id: LeaseId,
  /// Secret opaque fence returned with the Lease.
  pub fence: LeaseFence,
  /// Stable Agent identity.
  pub agent_id: AgentId,
  /// Current Agent process epoch.
  pub registration_epoch: RegistrationEpoch,
}

/// Complete atomic input for one fenced Lease heartbeat.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RenewLease {
  /// Stable identity used to replay an identical heartbeat.
  pub idempotency_key: crate::IdempotencyKey,
  /// Current fenced Lease authority.
  pub lease: LeaseAccess,
  /// Job identity echoed by the Agent's Lease assignment.
  pub job_id: JobId,
  /// Attempt number echoed by the Agent's Lease assignment.
  pub attempt: AttemptNumber,
  /// Authoritative time at which the heartbeat was accepted.
  pub observed_at: Timestamp,
  /// New exclusive Lease deadline when renewal is allowed.
  pub expires_at: Timestamp,
}

impl RenewLease {
  /// Revalidates the proposed renewal window at an adapter seam.
  pub fn validate(&self) -> Result<(), StoreError> {
    if self.expires_at <= self.observed_at {
      return Err(StoreError::invalid(
        StoreOperation::RenewLease,
        StoreInputError::InvalidLeaseWindow,
      ));
    }
    Ok(())
  }
}

/// Authoritative control decision returned by one Lease heartbeat.
#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub enum LeaseHeartbeatOutcome {
  /// Continue execution under the renewed deadline.
  Continue {
    /// Exclusive renewed Lease deadline.
    expires_at: Timestamp,
  },
  /// Cooperatively cancel the current Job.
  Cancel,
  /// Stop immediately because Lease ownership is no longer current.
  Fenced,
  /// Finish current work under the renewed deadline and accept no more work.
  Drain {
    /// Exclusive renewed Lease deadline.
    expires_at: Timestamp,
  },
}

/// One immutable ordered Job event and its exact payload identity.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DurableJobEvent {
  /// Positive sequence within one Job stream.
  sequence: EventSequence,
  /// Stable provider-neutral event classification.
  kind: JobEventKind,
  /// Source-observed time retained independently of persistence time.
  occurred_at: Timestamp,
  /// Bounded validated event payload.
  payload: Value,
  /// Digest of the canonical event kind, time, and bounded payload.
  digest: EventDigest,
}

impl DurableJobEvent {
  /// Validates the payload and computes its canonical event digest.
  pub fn new(
    sequence: EventSequence,
    kind: JobEventKind,
    occurred_at: Timestamp,
    payload: Value,
  ) -> Result<Self, StoreInputError> {
    require_bounded_json(
      &payload,
      MAX_JOB_EVENT_PAYLOAD_BYTES,
      StoreInputError::EventPayloadTooLarge,
    )?;
    let canonical_payload = canonicalize_json(payload).map_err(|_| StoreInputError::JsonDocumentTooDeep)?;
    let encoded = serde_json::to_vec(&(kind.as_str(), occurred_at.unix_millis(), &canonical_payload))
      .map_err(|_| StoreInputError::EventPayloadTooLarge)?;
    let digest = EventDigest::from_bytes(Sha256::digest(encoded).into());
    Ok(Self {
      sequence,
      kind,
      occurred_at,
      payload: canonical_payload,
      digest,
    })
  }

  /// Returns the positive sequence within the Job stream.
  #[must_use]
  pub const fn sequence(&self) -> EventSequence {
    self.sequence
  }

  /// Returns the stable provider-neutral event classification.
  #[must_use]
  pub const fn kind(&self) -> &JobEventKind {
    &self.kind
  }

  /// Returns the source-observed event time.
  #[must_use]
  pub const fn occurred_at(&self) -> Timestamp {
    self.occurred_at
  }

  /// Borrows the validated canonical payload.
  #[must_use]
  pub const fn payload(&self) -> &Value {
    &self.payload
  }

  /// Returns the digest computed from the complete canonical event content.
  #[must_use]
  pub const fn digest(&self) -> EventDigest {
    self.digest
  }
}

/// Complete atomic input for one contiguous idempotent Job-event append.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AppendJobEvents {
  /// Current fenced ownership.
  pub lease: LeaseAccess,
  /// Contiguous batch, which may include an already durable replay prefix.
  pub events: Vec<DurableJobEvent>,
  /// Verified immutable chunks covering only newly accepted stdout/stderr events.
  pub log_chunks: Vec<LogChunkManifest>,
  /// Authoritative acceptance time used to reject expired Lease ownership.
  pub accepted_at: Timestamp,
}

impl AppendJobEvents {
  /// Validates sequence continuity within one batch.
  pub fn new(lease: LeaseAccess, events: Vec<DurableJobEvent>, accepted_at: Timestamp) -> Result<Self, StoreError> {
    let request = Self {
      lease,
      events,
      log_chunks: Vec::new(),
      accepted_at,
    };
    request.validate()?;
    Ok(request)
  }

  /// Attaches verified chunk manifests prepared after reading the durable cursor.
  pub fn with_log_chunks(mut self, log_chunks: Vec<LogChunkManifest>) -> Result<Self, StoreError> {
    self.log_chunks = log_chunks;
    self.validate()?;
    Ok(self)
  }

  /// Revalidates the batch bound and sequence continuity at an adapter seam.
  pub fn validate(&self) -> Result<(), StoreError> {
    let events = &self.events;
    if events.is_empty() {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::EmptyEventBatch,
      ));
    }
    if events.len() > MAX_JOB_EVENT_BATCH_SIZE {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::EventBatchTooLarge,
      ));
    }
    if events
      .iter()
      .try_fold(0_usize, |total, event| {
        serde_json::to_vec(&(
          event.sequence().get(),
          event.kind().as_str(),
          event.occurred_at().unix_millis(),
          event.payload(),
        ))
        .ok()
        .and_then(|encoded| total.checked_add(encoded.len()))
      })
      .is_none_or(|bytes| bytes > MAX_JOB_EVENT_BATCH_BYTES)
    {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::RequestTooLarge,
      ));
    }
    if events
      .windows(2)
      .any(|pair| pair[0].sequence().get().checked_add(1) != Some(pair[1].sequence().get()))
    {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::NonContiguousEventBatch,
      ));
    }
    let first_sequence = events[0].sequence().get();
    let last_sequence = events[events.len() - 1].sequence().get();
    let mut ranges: Vec<_> = self
      .log_chunks
      .iter()
      .map(|chunk| (chunk.first_sequence(), chunk.last_sequence()))
      .collect();
    ranges.sort_unstable();
    if ranges
      .iter()
      .any(|(first, last)| *first < first_sequence || *last > last_sequence || *first == 0 || *last < *first)
      || ranges.windows(2).any(|pair| pair[0].1 >= pair[1].0)
    {
      return Err(StoreError::invalid(
        StoreOperation::AppendJobEvents,
        StoreInputError::InvalidLogChunkManifest,
      ));
    }
    Ok(())
  }
}

/// Cursor observed before writing immutable log objects.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct JobEventAppendPreparation {
  /// Greatest contiguous event sequence already durable, or zero.
  pub durable_through: u64,
}

/// Validates that manifests cover every newly accepted log event exactly once.
pub fn validate_new_log_chunks(
  events: &[DurableJobEvent],
  durable_through: u64,
  chunks: &[LogChunkManifest],
) -> Result<(), StoreError> {
  let expected: Vec<_> = events
    .iter()
    .filter(|event| event.sequence().get() > durable_through)
    .filter_map(|event| match event.kind().as_str() {
      "stdout" => Some((event.sequence().get(), BuildLogStream::Stdout)),
      "stderr" => Some((event.sequence().get(), BuildLogStream::Stderr)),
      _ => None,
    })
    .collect();
  let mut covered = Vec::new();
  for chunk in chunks {
    if chunk.first_sequence() <= durable_through {
      return invalid_log_chunks();
    }
    for sequence in chunk.first_sequence()..=chunk.last_sequence() {
      covered.push((sequence, chunk.stream()));
    }
  }
  covered.sort_unstable();
  let mut expected = expected;
  expected.sort_unstable();
  if covered != expected {
    return invalid_log_chunks();
  }
  Ok(())
}

fn invalid_log_chunks<T>() -> Result<T, StoreError> {
  Err(StoreError::invalid(
    StoreOperation::AppendJobEvents,
    StoreInputError::InvalidLogChunkManifest,
  ))
}

/// Durable cursor returned after one event append.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct AppendJobEventsOutcome {
  /// Greatest contiguous sequence now durable.
  pub acknowledged_through: EventSequence,
  /// Number of newly inserted events; an exact replay inserts zero.
  pub inserted: usize,
}

/// Bounded durable read after one caller-observed Job-event sequence.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ReadJobEvents {
  /// Job whose immutable event stream is requested.
  pub job_id: JobId,
  /// Greatest sequence already observed by the caller; zero starts the stream.
  pub after_sequence: u64,
  /// Maximum number of events returned by one store operation.
  pub limit: u16,
}

impl ReadJobEvents {
  /// Creates one validated bounded Job-event read.
  pub fn new(job_id: JobId, after_sequence: u64, limit: u16) -> Result<Self, StoreError> {
    let request = Self {
      job_id,
      after_sequence,
      limit,
    };
    request.validate()?;
    Ok(request)
  }

  /// Revalidates the page bound at an adapter seam.
  pub fn validate(self) -> Result<(), StoreError> {
    if self.limit == 0 || usize::from(self.limit) > MAX_JOB_EVENT_READ_PAGE_SIZE {
      return Err(StoreError::invalid(
        StoreOperation::ReadJobEvents,
        StoreInputError::InvalidJobEventPageSize,
      ));
    }
    Ok(())
  }
}

/// One ordered durable Job-event page and its resumable sequence cursor.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JobEventPage {
  /// Contiguous events after the requested sequence, in ascending order.
  pub events: Vec<DurableJobEvent>,
  /// Last returned sequence, or the current durable stream cursor when empty.
  pub cursor: u64,
}

/// Stable terminal classification stored for one completed Job.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum JobCompletionKind {
  /// The Job completed successfully.
  Succeeded,
  /// The Job completed with a classified execution failure.
  Failed(JobFailureClass),
  /// The Job reached terminal cancellation.
  Cancelled,
}

impl JobCompletionKind {
  /// Returns the durable failure class carried by an unsuccessful completion.
  #[must_use]
  pub const fn failure_class(self) -> Option<JobFailureClass> {
    match self {
      Self::Failed(class) => Some(class),
      Self::Succeeded | Self::Cancelled => None,
    }
  }
}

/// Applies the explicit execution and terminal facts represented by an Agent
/// completion to the durable Job state machine.
pub fn complete_job_state(current: JobState, kind: JobCompletionKind) -> Result<JobState, StoreError> {
  let running = start_job_execution(current)?;
  let event = match kind {
    JobCompletionKind::Succeeded => JobEvent::Succeed,
    JobCompletionKind::Failed(_) => JobEvent::Fail,
    JobCompletionKind::Cancelled => JobEvent::Cancel,
  };
  running.transition(event).map_err(|_| StoreError::Conflict {
    entity: octacity_server_domain::EntityKind::Job,
  })
}

/// Applies the persisted execution-start fact while allowing later Agent
/// deliveries to observe an already running or cancelling Job idempotently.
pub fn start_job_execution(current: JobState) -> Result<JobState, StoreError> {
  match current {
    JobState::Leased => current
      .transition(JobEvent::ExecutionStarted)
      .map_err(|_| StoreError::Unavailable),
    JobState::Running | JobState::Cancelling => Ok(current),
    _ => Err(StoreError::Conflict {
      entity: octacity_server_domain::EntityKind::Job,
    }),
  }
}

/// Complete atomic input for terminal Job completion.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct JobCompletion {
  /// Stable caller identity reused after a lost completion acknowledgement.
  pub completion_id: crate::IdempotencyKey,
  /// Current fenced ownership.
  pub lease: LeaseAccess,
  /// Greatest event sequence declared by the Agent, or `None` for no events.
  pub final_sequence: Option<EventSequence>,
  /// Terminal outcome.
  pub kind: JobCompletionKind,
  /// Authoritative completion time.
  pub completed_at: Timestamp,
}

/// Result of an idempotent terminal completion.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CompletionDisposition {
  /// Whether the completion was newly applied or exactly replayed.
  pub disposition: MutationDisposition,
  /// Completed Job identity.
  pub job_id: JobId,
  /// Authoritative failure class persisted for an unsuccessful execution.
  pub failure_class: Option<JobFailureClass>,
  /// Dependency-unblocked Jobs inserted into the ready queue by this commit.
  pub ready_jobs: Vec<JobId>,
  /// Pools eligible for at least one newly ready Job.
  pub ready_pools: BTreeSet<PoolId>,
  /// Jobs made terminal by dependency failure propagation in this commit.
  pub skipped_jobs: Vec<JobId>,
  /// Attempt state derived from the complete post-transition graph.
  pub attempt_state: AttemptState,
  /// Build state derived from the current Attempt state.
  pub build_state: BuildState,
}
