use octacity_server_application::{
  CreateBuildConfigurationCommand, CreatePipelineCommand, CreateProjectCommand, CreateRepositoryCommand,
  DeleteProjectCommand, GetBuildConfigurationQuery, GetPipelineQuery, GetProjectQuery, GetRepositoryQuery,
  ListProjectsQuery, MoveProjectCommand, PublishBuildConfigurationVersionCommand, PublishPipelineVersionCommand,
  PublishProjectPolicyCommand, PublishRepositoryVersionCommand, RenameProjectCommand,
};

use super::{ManagementOperation, ParameterProfile};

pub(super) const OPERATIONS: &[ManagementOperation] = &[
  operation!(
    CreateProjectCommand,
    "POST",
    "/api/v1/projects",
    "createProject",
    "Projects",
    "Create a Project",
    Some("CreateProjectRequest"),
    "ProjectMutationResponse",
    "201",
    true,
    false
  ),
  operation!(
    ListProjectsQuery,
    "GET",
    "/api/v1/projects",
    "listProjects",
    "Projects",
    "List Projects",
    None,
    "ProjectPage",
    "200",
    false,
    false
  )
  .with_parameters(ParameterProfile::ProjectList)
  .with_visibility::<ListProjectsQuery>(),
  operation!(
    GetProjectQuery,
    "GET",
    "/api/v1/projects/{project_id}",
    "getProject",
    "Projects",
    "Get a Project",
    None,
    "ProjectDetails",
    "200",
    false,
    false
  ),
  operation!(
    DeleteProjectCommand,
    "DELETE",
    "/api/v1/projects/{project_id}",
    "deleteProject",
    "Projects",
    "Delete a Project",
    None,
    "DeleteProjectResponse",
    "200",
    true,
    true
  ),
  operation!(
    RenameProjectCommand,
    "POST",
    "/api/v1/projects/{project_id}/rename",
    "renameProject",
    "Projects",
    "Rename a Project",
    Some("RenameProjectRequest"),
    "ProjectMutationResponse",
    "200",
    true,
    true
  ),
  operation!(
    MoveProjectCommand,
    "POST",
    "/api/v1/projects/{project_id}/move",
    "moveProject",
    "Projects",
    "Move a Project",
    Some("MoveProjectRequest"),
    "ProjectMutationResponse",
    "200",
    true,
    true
  ),
  operation!(
    PublishProjectPolicyCommand,
    "POST",
    "/api/v1/projects/{project_id}/policy-versions",
    "publishProjectPolicyVersion",
    "Projects",
    "Publish a Project policy version",
    Some("PublishProjectPolicyRequest"),
    "ProjectPolicyMutationResponse",
    "201",
    true,
    false
  ),
  operation!(
    CreatePipelineCommand,
    "POST",
    "/api/v1/pipelines",
    "createPipeline",
    "Pipelines",
    "Create a Pipeline",
    Some("CreatePipelineRequest"),
    "PipelineMutationResponse",
    "201",
    true,
    false
  ),
  operation!(
    PublishPipelineVersionCommand,
    "POST",
    "/api/v1/pipelines/{pipeline_id}/versions",
    "publishPipelineVersion",
    "Pipelines",
    "Publish a Pipeline version",
    Some("PublishPipelineVersionRequest"),
    "PipelineMutationResponse",
    "200",
    true,
    true
  ),
  operation!(
    GetPipelineQuery,
    "GET",
    "/api/v1/pipelines/{pipeline_id}/versions/{version}",
    "getPipelineVersion",
    "Pipelines",
    "Get a Pipeline version",
    None,
    "PipelineResource",
    "200",
    false,
    false
  ),
  operation!(
    CreateRepositoryCommand,
    "POST",
    "/api/v1/repositories",
    "createRepository",
    "Repositories",
    "Create a Repository",
    Some("CreateRepositoryRequest"),
    "RepositoryMutationResponse",
    "201",
    true,
    false
  ),
  operation!(
    PublishRepositoryVersionCommand,
    "POST",
    "/api/v1/repositories/{repository_id}/versions",
    "publishRepositoryVersion",
    "Repositories",
    "Publish a Repository version",
    Some("PublishRepositoryVersionRequest"),
    "RepositoryMutationResponse",
    "200",
    true,
    true
  ),
  operation!(
    GetRepositoryQuery,
    "GET",
    "/api/v1/repositories/{repository_id}/versions/{version}",
    "getRepositoryVersion",
    "Repositories",
    "Get a Repository version",
    None,
    "RepositoryResource",
    "200",
    false,
    false
  ),
  operation!(
    CreateBuildConfigurationCommand,
    "POST",
    "/api/v1/build-configurations",
    "createBuildConfiguration",
    "Build Configurations",
    "Create a Build Configuration",
    Some("CreateBuildConfigurationRequest"),
    "BuildConfigurationMutationResponse",
    "201",
    true,
    false
  ),
  operation!(
    PublishBuildConfigurationVersionCommand,
    "POST",
    "/api/v1/build-configurations/{configuration_id}/versions",
    "publishBuildConfigurationVersion",
    "Build Configurations",
    "Publish a Build Configuration version",
    Some("PublishBuildConfigurationVersionRequest"),
    "BuildConfigurationMutationResponse",
    "200",
    true,
    true
  ),
  operation!(
    GetBuildConfigurationQuery,
    "GET",
    "/api/v1/build-configurations/{configuration_id}/versions/{version}",
    "getBuildConfigurationVersion",
    "Build Configurations",
    "Get a Build Configuration version",
    None,
    "BuildConfigurationResource",
    "200",
    false,
    false
  ),
];
