use std::fmt;

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use zeroize::{Zeroize as _, Zeroizing};

use super::{CoordinatorProtocolError, validation};

/// Exact byte length of enrollment and registration bearer secrets.
pub const AGENT_CREDENTIAL_SECRET_BYTES: usize = 32;

/// Authority represented by one Agent bearer token.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AgentCredentialKind {
  /// Single-use authority to create an Agent's first process registration.
  Enrollment,
  /// Authority of the currently registered Agent process.
  Registration,
}

/// Parsed Agent bearer token with protected secret formatting.
#[derive(Clone, Eq, PartialEq)]
pub struct AgentCredentialToken {
  kind: AgentCredentialKind,
  credential_id: String,
  secret: Zeroizing<[u8; AGENT_CREDENTIAL_SECRET_BYTES]>,
}

impl AgentCredentialToken {
  /// Constructs a single-use enrollment token from a stable credential identity
  /// and 256 bits generated by a cryptographically secure source.
  pub fn enrollment(
    credential_id: impl Into<String>,
    secret: [u8; AGENT_CREDENTIAL_SECRET_BYTES],
  ) -> Result<Self, CoordinatorProtocolError> {
    let credential_id = credential_id.into();
    validation::identifier("credential_id", &credential_id)?;
    Ok(Self {
      kind: AgentCredentialKind::Enrollment,
      credential_id,
      secret: Zeroizing::new(secret),
    })
  }

  /// Constructs a single-use enrollment token from its management-wire
  /// secret representation, consuming and clearing the encoded input.
  pub fn enrollment_base64url(
    credential_id: impl Into<String>,
    mut encoded_secret: String,
  ) -> Result<Self, CoordinatorProtocolError> {
    let decoded = URL_SAFE_NO_PAD.decode(encoded_secret.as_bytes());
    encoded_secret.zeroize();
    let mut decoded =
      Zeroizing::new(decoded.map_err(|_| CoordinatorProtocolError::new("agent credential secret is invalid"))?);
    let secret: [u8; AGENT_CREDENTIAL_SECRET_BYTES] = decoded
      .as_slice()
      .try_into()
      .map_err(|_| CoordinatorProtocolError::new("agent credential secret is invalid"))?;
    decoded.zeroize();
    Self::enrollment(credential_id, secret)
  }

  /// Parses `enrollment.<id>.<secret>` or `registration.<id>.<secret>`.
  pub fn parse(value: &str) -> Result<Self, CoordinatorProtocolError> {
    let mut parts = value.split('.');
    let kind = match parts.next() {
      Some("enrollment") => AgentCredentialKind::Enrollment,
      Some("registration") => AgentCredentialKind::Registration,
      _ => return validation::invalid("agent credential kind is invalid"),
    };
    let credential_id = parts
      .next()
      .ok_or_else(|| CoordinatorProtocolError::new("agent credential identity is missing"))?;
    let encoded_secret = parts
      .next()
      .ok_or_else(|| CoordinatorProtocolError::new("agent credential secret is missing"))?;
    if parts.next().is_some() {
      return validation::invalid("agent credential has unexpected components");
    }
    validation::identifier("agent credential identity", credential_id)?;
    let mut decoded = Zeroizing::new(
      URL_SAFE_NO_PAD
        .decode(encoded_secret)
        .map_err(|_| CoordinatorProtocolError::new("agent credential secret is invalid"))?,
    );
    let secret: [u8; AGENT_CREDENTIAL_SECRET_BYTES] = decoded
      .as_slice()
      .try_into()
      .map_err(|_| CoordinatorProtocolError::new("agent credential secret is invalid"))?;
    decoded.zeroize();
    Ok(Self {
      kind,
      credential_id: credential_id.to_owned(),
      secret: Zeroizing::new(secret),
    })
  }

  /// Returns whether the token carries enrollment or registration authority.
  #[must_use]
  pub const fn kind(&self) -> AgentCredentialKind {
    self.kind
  }

  /// Returns the non-secret credential identity.
  #[must_use]
  pub fn credential_id(&self) -> &str {
    &self.credential_id
  }

  /// Borrows the protected secret for credential verification.
  #[must_use]
  pub fn secret(&self) -> &[u8; AGENT_CREDENTIAL_SECRET_BYTES] {
    &self.secret
  }

  /// Promotes a successfully used token to current-registration authority.
  pub fn promote(&self, registration_id: impl Into<String>) -> Result<Self, CoordinatorProtocolError> {
    let registration_id = registration_id.into();
    validation::identifier("registration_id", &registration_id)?;
    Ok(Self {
      kind: AgentCredentialKind::Registration,
      credential_id: registration_id,
      secret: self.secret.clone(),
    })
  }

  /// Encodes the token for an HTTP bearer header without logging it.
  #[must_use]
  pub fn encode(&self) -> Zeroizing<String> {
    let kind = match self.kind {
      AgentCredentialKind::Enrollment => "enrollment",
      AgentCredentialKind::Registration => "registration",
    };
    Zeroizing::new(format!(
      "{kind}.{}.{}",
      self.credential_id,
      URL_SAFE_NO_PAD.encode(self.secret.as_slice())
    ))
  }
}

impl fmt::Debug for AgentCredentialToken {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter
      .debug_struct("AgentCredentialToken")
      .field("kind", &self.kind)
      .field("credential_id", &self.credential_id)
      .field("secret", &"[REDACTED]")
      .finish()
  }
}
